/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PercepcoesRouteImport } from './routes/percepcoes'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IaRouteImport } from './routes/ia'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EcossistemaRouteImport } from './routes/ecossistema'
import { Route as DiferenciaisRouteImport } from './routes/diferenciais'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CasosDeUsoRouteImport } from './routes/casos-de-uso'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesSlugRouteImport } from './routes/solucoes.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PercepcoesRoute = PercepcoesRouteImport.update({
  id: '/percepcoes',
  path: '/percepcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EcossistemaRoute = EcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => rootRouteImport,
} as any)
const DiferenciaisRoute = DiferenciaisRouteImport.update({
  id: '/diferenciais',
  path: '/diferenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosDeUsoRoute = CasosDeUsoRouteImport.update({
  id: '/casos-de-uso',
  path: '/casos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSlugRoute = SolucoesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolucoesRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/casos-de-uso': typeof CasosDeUsoRoute
  '/contato': typeof ContatoRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/ecossistema': typeof EcossistemaRoute
  '/equipe': typeof EquipeRoute
  '/ia': typeof IaRoute
  '/mcp': typeof McpRoute
  '/metodologia': typeof MetodologiaRoute
  '/percepcoes': typeof PercepcoesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/casos-de-uso': typeof CasosDeUsoRoute
  '/contato': typeof ContatoRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/ecossistema': typeof EcossistemaRoute
  '/equipe': typeof EquipeRoute
  '/ia': typeof IaRoute
  '/mcp': typeof McpRoute
  '/metodologia': typeof MetodologiaRoute
  '/percepcoes': typeof PercepcoesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/casos-de-uso': typeof CasosDeUsoRoute
  '/contato': typeof ContatoRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/ecossistema': typeof EcossistemaRoute
  '/equipe': typeof EquipeRoute
  '/ia': typeof IaRoute
  '/mcp': typeof McpRoute
  '/metodologia': typeof MetodologiaRoute
  '/percepcoes': typeof PercepcoesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/solucoes': typeof SolucoesRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/casos-de-uso'
    | '/contato'
    | '/diferenciais'
    | '/ecossistema'
    | '/equipe'
    | '/ia'
    | '/mcp'
    | '/metodologia'
    | '/percepcoes'
    | '/quem-somos'
    | '/solucoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/solucoes/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/casos-de-uso'
    | '/contato'
    | '/diferenciais'
    | '/ecossistema'
    | '/equipe'
    | '/ia'
    | '/mcp'
    | '/metodologia'
    | '/percepcoes'
    | '/quem-somos'
    | '/solucoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/solucoes/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/casos-de-uso'
    | '/contato'
    | '/diferenciais'
    | '/ecossistema'
    | '/equipe'
    | '/ia'
    | '/mcp'
    | '/metodologia'
    | '/percepcoes'
    | '/quem-somos'
    | '/solucoes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/solucoes/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CasosDeUsoRoute: typeof CasosDeUsoRoute
  ContatoRoute: typeof ContatoRoute
  DiferenciaisRoute: typeof DiferenciaisRoute
  EcossistemaRoute: typeof EcossistemaRoute
  EquipeRoute: typeof EquipeRoute
  IaRoute: typeof IaRoute
  McpRoute: typeof McpRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PercepcoesRoute: typeof PercepcoesRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SolucoesRoute: typeof SolucoesRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percepcoes': {
      id: '/percepcoes'
      path: '/percepcoes'
      fullPath: '/percepcoes'
      preLoaderRoute: typeof PercepcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecossistema': {
      id: '/ecossistema'
      path: '/ecossistema'
      fullPath: '/ecossistema'
      preLoaderRoute: typeof EcossistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diferenciais': {
      id: '/diferenciais'
      path: '/diferenciais'
      fullPath: '/diferenciais'
      preLoaderRoute: typeof DiferenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos-de-uso': {
      id: '/casos-de-uso'
      path: '/casos-de-uso'
      fullPath: '/casos-de-uso'
      preLoaderRoute: typeof CasosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/$slug': {
      id: '/solucoes/$slug'
      path: '/$slug'
      fullPath: '/solucoes/$slug'
      preLoaderRoute: typeof SolucoesSlugRouteImport
      parentRoute: typeof SolucoesRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolucoesRouteChildren {
  SolucoesSlugRoute: typeof SolucoesSlugRoute
}

const SolucoesRouteChildren: SolucoesRouteChildren = {
  SolucoesSlugRoute: SolucoesSlugRoute,
}

const SolucoesRouteWithChildren = SolucoesRoute._addFileChildren(
  SolucoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CasosDeUsoRoute: CasosDeUsoRoute,
  ContatoRoute: ContatoRoute,
  DiferenciaisRoute: DiferenciaisRoute,
  EcossistemaRoute: EcossistemaRoute,
  EquipeRoute: EquipeRoute,
  IaRoute: IaRoute,
  McpRoute: McpRoute,
  MetodologiaRoute: MetodologiaRoute,
  PercepcoesRoute: PercepcoesRoute,
  QuemSomosRoute: QuemSomosRoute,
  SolucoesRoute: SolucoesRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
